name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  erlang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.0"
          gleam-version: "1.10.0"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
  javascript-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          gleam-version: "1.10.0"
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: gleam deps download
      - run: gleam test --target javascript --runtime node
      - run: gleam format --check src test
  javascript-bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: erlef/setup-beam@v1
        with:
          gleam-version: "1.10.0"
      - run: gleam deps download
      - run: gleam test --target javascript --runtime bun
      - run: gleam format --check src test
